#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

IFS=$'\n'

prefix=$(readlink -f ${PASSWORD_STORE_DIR-~/.password-store})
password_files=( $( fd -L ".gpg\$" "$prefix" ) )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$( printf '%s\n' "${password_files[@]}" | wofi -i -k /dev/null -d menu -- "$@" )

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password"
    notify-send -t 5000 "$(echo "$password copied to clipboard")"
fi
